stages:
  - images
  - checklist

include:
  - /build/ci/gitlab/jobs.yml
  - /build/ci/gitlab/images.yml

############################################################################## images

# jobs from build/ci/gitlab/images.yml

############################################################################## checklist

gitflow:
  extends: .lightweight-job
  stage: checklist
  script:
    - git remote update
    - if ! git log --pretty=format:"%H" | grep $(git log --pretty=format:"%H" -n 1 origin/master); then exit 1; fi
  except:
    - master
    - tags
    - schedules

conflicts:
  extends: .lightweight-job
  stage: checklist
  script:
    - if grep -rni '^<<<\<<<< '; then exit 1; fi
    - if grep -rni '^===\====$'; then exit 1; fi
    - if grep -rni '^>>>\>>>> '; then exit 1; fi
  except:
    - schedules
    - tags

todos:
  extends: .lightweight-job
  stage: checklist
  script:
    - if grep -rni '@to\do:'; then exit 1; fi
  allow_failure: true
  except:
    - schedules
    - tags

unit-tests:
  extends: .base-image
  image: ${CI_REGISTRY_IMAGE}/golang:1.15-alpine-env
  stage: checklist
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'
  script:
    - make test
    - go tool cover -func=coverage.out
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-coverage
    expire_in: 1 day
    when: on_success
    paths:
      - coverage.html
  except:
    - schedules
    - tags
  allow_failure: true # @TODO: remove

linters:
  extends: .base-image
  image: ${CI_REGISTRY_IMAGE}/golang:1.15-alpine-env
  stage: checklist
  script:
    - make lint
  except:
    - schedules
    - tags
  allow_failure: true # @TODO: remove
